# Generated by Django 4.2.4 on 2023-11-27 19:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_packaging", "0001_initial"),
        ("core_warehouse", "0001_initial"),
        ("core_client", "0001_initial"),
        ("core_product", "0001_initial"),
        ("core_carrier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockOut",
            fields=[
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "flux",
                    models.CharField(
                        choices=[("IMP", "Import"), ("EXP", "Export")],
                        default="",
                        max_length=5,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("display_id", models.IntegerField(default=1)),
                (
                    "shipment_num",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "type_gestion",
                    models.CharField(
                        choices=[("LT", "Lot"), ("MA", "Masse"), ("VR", "Vrac")],
                        default="LT",
                        max_length=5,
                    ),
                ),
                ("nbr_lot", models.PositiveIntegerField(blank=True, null=True)),
                ("campagne", models.CharField(blank=True, default="", max_length=5)),
                ("num_contrat", models.CharField(blank=True, default="", max_length=5)),
                ("date_exit", models.DateField()),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "num_immatricule",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "num_bordereau",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "num_remorque",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "nom_superviseur",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "nom_gardien",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "nom_chauffeur",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "permis_conduire",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("num_lot", models.CharField(blank=True, default="", max_length=50)),
                ("quality", models.CharField(blank=True, default="", max_length=50)),
                ("grade", models.CharField(blank=True, default="", max_length=50)),
                ("conformity", models.CharField(blank=True, default="", max_length=50)),
                (
                    "poids_theorique",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "poids_reel",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("transaction_type", models.CharField(default="OUT", max_length=3)),
                (
                    "carrier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_carrier.carrier",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_client.client",
                    ),
                ),
                (
                    "packaging",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_packaging.packaging",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_product.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "unique_together": {("product", "warehouse", "client", "created")},
            },
        ),
        migrations.CreateModel(
            name="StockIn",
            fields=[
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "flux",
                    models.CharField(
                        choices=[("IMP", "Import"), ("EXP", "Export")],
                        default="",
                        max_length=5,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("display_id", models.IntegerField(default=1)),
                (
                    "shipment_num",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "type_gestion",
                    models.CharField(
                        choices=[("LT", "Lot"), ("MA", "Masse"), ("VR", "Vrac")],
                        default="LT",
                        max_length=5,
                    ),
                ),
                ("nbr_lot", models.PositiveIntegerField(blank=True, null=True)),
                ("campagne", models.CharField(blank=True, default="", max_length=5)),
                ("num_contrat", models.CharField(blank=True, default="", max_length=5)),
                ("date_entry", models.DateField()),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "num_immatricule",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "num_bordereau",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "num_remorque",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "nom_superviseur",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "nom_gardien",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "nom_chauffeur",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "permis_conduire",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("num_lot", models.CharField(blank=True, default="", max_length=50)),
                ("quality", models.CharField(blank=True, default="", max_length=50)),
                ("grade", models.CharField(blank=True, default="", max_length=50)),
                ("conformity", models.CharField(blank=True, default="", max_length=50)),
                (
                    "poids_theorique",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "poids_reel",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("transaction_type", models.CharField(default="IN", max_length=3)),
                (
                    "carrier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_carrier.carrier",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_client.client",
                    ),
                ),
                (
                    "packaging",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_packaging.packaging",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_product.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "unique_together": {("product", "warehouse", "client", "created")},
            },
        ),
    ]
