# Generated by Django 4.2.4 on 2023-11-27 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_product", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("client_name", models.CharField(max_length=50, unique=True)),
                (
                    "client_ref",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "client_address",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "client_email",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "client_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "products",
                    models.ManyToManyField(blank=True, to="core_product.product"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
