# Generated by Django 4.2.4 on 2023-11-27 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "carrier_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Name of Carrier"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
